package com.hand.user.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "y_hap_demo_assign")
public class HapDemoAssign extends BaseDTO {

     public static final String FIELD_ASSIGN_ID = "assignId";
     public static final String FIELD_EMPLOYEE_ID = "employeeId";
     public static final String FIELD_POSITION_ID = "positionId";
     public static final String FIELD_PRIMARY_POSITION_FLAG = "primaryPositionFlag";
     public static final String FIELD_ENABLED_FLAG = "enabledFlag";


     @Id
     @GeneratedValue
     private Long assignId;

     @NotNull
     private Long employeeId; //员工ID

     @NotNull
     private Long positionId; //岗位ID

     @Length(max = 1)
     private String primaryPositionFlag; //主岗位标示

     @NotEmpty
     @Length(max = 1)
     private String enabledFlag; //启用状态


     public void setAssignId(Long assignId){
         this.assignId = assignId;
     }

     public Long getAssignId(){
         return assignId;
     }

     public void setEmployeeId(Long employeeId){
         this.employeeId = employeeId;
     }

     public Long getEmployeeId(){
         return employeeId;
     }

     public void setPositionId(Long positionId){
         this.positionId = positionId;
     }

     public Long getPositionId(){
         return positionId;
     }

     public void setPrimaryPositionFlag(String primaryPositionFlag){
         this.primaryPositionFlag = primaryPositionFlag;
     }

     public String getPrimaryPositionFlag(){
         return primaryPositionFlag;
     }

     public void setEnabledFlag(String enabledFlag){
         this.enabledFlag = enabledFlag;
     }

     public String getEnabledFlag(){
         return enabledFlag;
     }

     }
