package com.hand.user.dto;

/**Auto Generated By Hap Code Generator**/

import com.fasterxml.jackson.annotation.JsonFormat;
import com.hand.hap.core.annotation.AuditEnabled;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.Length;
import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.util.Date;
@ExtensionAttribute(disable=true)
@AuditEnabled
@Table(name = "y_hap_demo")
public class HapDemo extends BaseDTO {

     public static final String FIELD_DEMO_ID = "demoId";
     public static final String FIELD_NAME = "name";
     public static final String FIELD_EMAIL = "email";
     public static final String FIELD_PHONE = "phone";
     public static final String FIELD_START_ACTIVE_DATE = "startActiveDate";
     public static final String FIELD_END_ACTIVE_DATE = "endActiveDate";
     public static final String FIELD_STATUS = "status";

     
     
     
     

     @Id
     @GeneratedValue
     private String demoId;

    @Transient
    private String employeeCode;
    @Transient
    private String userName;

     
     @Length(max = 30)
     private String name;

     @Length(max = 40)
     private String email;

     @Length(max = 30)
     private String phone;
     @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
     @DateTimeFormat(pattern = "yyyy-MM-dd")
     private Date startActiveDate;
     @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
     @DateTimeFormat(pattern = "yyyy-MM-dd")
     private Date endActiveDate;

     @Length(max = 30)
     private String status;


    public String getDemoId() {
        return demoId;
    }

    public void setDemoId(String demoId) {
        this.demoId = demoId;
    }

    public void setName(String name){
         this.name = name;
     }

     public String getName(){
         return name;
     }

     public void setEmail(String email){
         this.email = email;
     }

     public String getEmail(){
         return email;
     }

     public void setPhone(String phone){
         this.phone = phone;
     }

     public String getPhone(){
         return phone;
     }

     public void setStartActiveDate(Date startActiveDate){
         this.startActiveDate = startActiveDate;
     }

     public Date getStartActiveDate(){
         return startActiveDate;
     }

     public void setEndActiveDate(Date endActiveDate){
         this.endActiveDate = endActiveDate;
     }

     public Date getEndActiveDate(){
         return endActiveDate;
     }

     public void setStatus(String status){
         this.status = status;
     }

     public String getStatus(){
         return status;
     }

    public String getEmployeeCode() {
        return employeeCode;
    }

    public void setEmployeeCode(String employeeCode) {
        this.employeeCode = employeeCode;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }
}
