
package com.map;


import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "activityWebService", targetNamespace = "http://impl.service.webservice.activity.hand.com/", wsdlLocation = "http://localhost:8080/ws/activityWebService?wsdl")
public class ActivityWebService_Service extends Service {

    private final static URL ACTIVITYWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException ACTIVITYWEBSERVICE_EXCEPTION;
    private final static QName ACTIVITYWEBSERVICE_QNAME = new QName("http://impl.service.webservice.activity.hand.com/", "activityWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ws/activityWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ACTIVITYWEBSERVICE_WSDL_LOCATION = url;
        ACTIVITYWEBSERVICE_EXCEPTION = e;
    }

    public ActivityWebService_Service() {
        super(__getWsdlLocation(), ACTIVITYWEBSERVICE_QNAME);
    }

    public ActivityWebService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ACTIVITYWEBSERVICE_QNAME, features);
    }

    public ActivityWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, ACTIVITYWEBSERVICE_QNAME);
    }

    public ActivityWebService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ACTIVITYWEBSERVICE_QNAME, features);
    }

    public ActivityWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ActivityWebService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ActivityWebService
     */
   @WebEndpoint(name = "activityWebServiceImplPort")
    public ActivityWebService getActivityWebServiceImplPort() {
        return super.getPort(new QName("http://impl.service.webservice.activity.hand.com/", "activityWebServiceImplPort"), ActivityWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ActivityWebService
     */
    @WebEndpoint(name = "activityWebServiceImplPort")
    public ActivityWebService getActivityWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.webservice.activity.hand.com/", "activityWebServiceImplPort"), ActivityWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ACTIVITYWEBSERVICE_EXCEPTION!= null) {
            throw ACTIVITYWEBSERVICE_EXCEPTION;
        }
        return ACTIVITYWEBSERVICE_WSDL_LOCATION;
    }

}
