
package com.map;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "activityWebService", targetNamespace = "http://service.webservice.activity.hand.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ActivityWebService {


    /**
     * 
     * @param result
     * @return
     *     returns com.map.CallProductVo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCallBack", targetNamespace = "http://service.webservice.activity.hand.com/", className = "com.map.GetCallBack")
    @ResponseWrapper(localName = "getCallBackResponse", targetNamespace = "http://service.webservice.activity.hand.com/", className = "com.map.GetCallBackResponse")
    public CallProductVo getCallBack(
            @WebParam(name = "result", targetNamespace = "")
                    RequestVo result);

}
