package com.hand.client.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;
import java.util.List;

@ExtensionAttribute(disable=true)
@Table(name = "yfs_gl_client")
public class GlClient extends BaseDTO {

     public static final String FIELD_GL_CLIENT_ID = "glClientId";
     public static final String FIELD_CLIENT_ID = "clientId";
     public static final String FIELD_APPLICATION_STATUS = "applicationStatus";
     public static final String FIELD_APPLICATION_DATE = "applicationDate";


     @Id
     @GeneratedValue
     private Long glClientId; //关联表ID

     private Long clientId; //客户表ID

    @Transient
    private String landerRole;
    @Transient
    private String clientby;
    @Transient
    private String activityname;

    private Long activityId; //活动ID
     @Length(max = 30)
     private String applicationStatus; //申请状态
    @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd")
     private Date applicationDate; //申请时间


    public String getLanderRole() {
        return landerRole;
    }

    public void setLanderRole(String landerRole) {
        this.landerRole = landerRole;
    }

    public Long getActivityId() {
        return activityId;
    }

    public void setActivityId(Long activityId) {
        this.activityId = activityId;
    }

    public String getClientby() {
        return clientby;
    }

    public void setClientby(String clientby) {
        this.clientby = clientby;
    }

    public String getActivityname() {
        return activityname;
    }

    public void setActivityname(String activityname) {
        this.activityname = activityname;
    }



    public void setGlClientId(Long glClientId){
         this.glClientId = glClientId;
     }

     public Long getGlClientId(){
         return glClientId;
     }

     public void setClientId(Long clientId){
         this.clientId = clientId;
     }

     public Long getClientId(){
         return clientId;
     }

     public void setApplicationStatus(String applicationStatus){
         this.applicationStatus = applicationStatus;
     }

     public String getApplicationStatus(){
         return applicationStatus;
     }

     public void setApplicationDate(Date applicationDate){
         this.applicationDate = applicationDate;
     }

    public Date getApplicationDate() {
        return applicationDate;
    }
}
