package com.hand.audit.dto;

/**Auto Generated By Hap Code Generator**/

import com.fasterxml.jackson.annotation.JsonFormat;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.Length;
import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "y_hap_demo_a")
public class HapDemoA extends BaseDTO {

     public static final String FIELD_AUDIT_ID = "auditId";
     public static final String FIELD_DEMO_ID = "demoId";
     public static final String FIELD_NAME = "name";
     public static final String FIELD_EMAIL = "email";
     public static final String FIELD_PHONE = "phone";
     public static final String FIELD_START_ACTIVE_DATE = "startActiveDate";
     public static final String FIELD_END_ACTIVE_DATE = "endActiveDate";
     public static final String FIELD_STATUS = "status";
     public static final String FIELD_AUDIT_TRANSACTION_TYPE = "auditTransactionType";
     public static final String FIELD_AUDIT_TIMESTAMP = "auditTimestamp";
     public static final String FIELD_AUDIT_SESSION_ID = "auditSessionId";
     public static final String FIELD_AUDIT_TAG = "auditTag";
     public static final String FIELD_LANG = "lang";


     @Id
     @GeneratedValue
     private Long auditId;

     private Long demoId;

     @Length(max = 30)
     private String name;

     @Length(max = 40)
     private String email;

     @Length(max = 30)
     private String phone;
    @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd")
     private Date startActiveDate;
    @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd")
     private Date endActiveDate;

     @Length(max = 30)
     private String status;

     @Length(max = 10)
     private String auditTransactionType;

     private Date auditTimestamp;

     @Length(max = 64)
     private String auditSessionId;

     private Long auditTag;

     @Length(max = 20)
     private String lang;


     public void setAuditId(Long auditId){
         this.auditId = auditId;
     }

     public Long getAuditId(){
         return auditId;
     }

     public void setDemoId(Long demoId){
         this.demoId = demoId;
     }

     public Long getDemoId(){
         return demoId;
     }

     public void setName(String name){
         this.name = name;
     }

     public String getName(){
         return name;
     }

     public void setEmail(String email){
         this.email = email;
     }

     public String getEmail(){
         return email;
     }

     public void setPhone(String phone){
         this.phone = phone;
     }

     public String getPhone(){
         return phone;
     }

     public void setStartActiveDate(Date startActiveDate){
         this.startActiveDate = startActiveDate;
     }

     public Date getStartActiveDate(){
         return startActiveDate;
     }

     public void setEndActiveDate(Date endActiveDate){
         this.endActiveDate = endActiveDate;
     }

     public Date getEndActiveDate(){
         return endActiveDate;
     }

     public void setStatus(String status){
         this.status = status;
     }

     public String getStatus(){
         return status;
     }

     public void setAuditTransactionType(String auditTransactionType){
         this.auditTransactionType = auditTransactionType;
     }

     public String getAuditTransactionType(){
         return auditTransactionType;
     }

     public void setAuditTimestamp(Date auditTimestamp){
         this.auditTimestamp = auditTimestamp;
     }

     public Date getAuditTimestamp(){
         return auditTimestamp;
     }

     public void setAuditSessionId(String auditSessionId){
         this.auditSessionId = auditSessionId;
     }

     public String getAuditSessionId(){
         return auditSessionId;
     }

     public void setAuditTag(Long auditTag){
         this.auditTag = auditTag;
     }

     public Long getAuditTag(){
         return auditTag;
     }

     public void setLang(String lang){
         this.lang = lang;
     }

     public String getLang(){
         return lang;
     }

     }
