package com.hand.activity.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "yfs_file")
public class File extends BaseDTO {

     public static final String FIELD_FILE_ID = "fileId";
     public static final String FIELD_ACTIVITY_ID = "activityId";
     public static final String FIELD_FILE_NAME = "fileName";
     public static final String FIELD_FILE_PATH = "filePath";
     public static final String FIELD_FILE_SIZE = "fileSize";
     public static final String FIELD_FILE_TYPE = "fileType";
     public static final String FIELD_UPLOAD_DATE = "uploadDate";


     @Id
     @GeneratedValue
     private Long fileId;

     private Long activityId; //附件ID

     private Long  attachmentId;

     @Length(max = 255)
     private String fileName; //文件名

     @Length(max = 255)
     private String filePath; //文件虚拟路径

     private Long fileSize; //文件大小

     @Length(max = 240)
     private String fileType; //文件类型

     private Date uploadDate; //上传时间


     public void setFileId(Long fileId){
         this.fileId = fileId;
     }

     public Long getFileId(){
         return fileId;
     }

     public void setActivityId(Long activityId){
         this.activityId = activityId;
     }

     public Long getActivityId(){
         return activityId;
     }

    public Long getAttachmentId() {
        return attachmentId;
    }

    public void setAttachmentId(Long attachmentId) {
        this.attachmentId = attachmentId;
    }

    public void setFileName(String fileName){
         this.fileName = fileName;
     }

     public String getFileName(){
         return fileName;
     }

     public void setFilePath(String filePath){
         this.filePath = filePath;
     }

     public String getFilePath(){
         return filePath;
     }

     public void setFileSize(Long fileSize){
         this.fileSize = fileSize;
     }

     public Long getFileSize(){
         return fileSize;
     }

     public void setFileType(String fileType){
         this.fileType = fileType;
     }

     public String getFileType(){
         return fileType;
     }

     public void setUploadDate(Date uploadDate){
         this.uploadDate = uploadDate;
     }

     public Date getUploadDate(){
         return uploadDate;
     }

     }
