package com.hand.activity.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "yfs_rent_activity")
public class RentActivity extends BaseDTO {

     public static final String FIELD_ACTIVITY_ID = "activityId";
     public static final String FIELD_EVENT_NAME = "eventName";
     public static final String FIELD_RELEASE_DATE = "releaseDate";
     public static final String FIELD_RELEASE_END_DATE = "releaseEndDate";
     public static final String FIELD_ACTIVE_STATUS = "activeStatus";
     public static final String FIELD_ACTIVITIES = "activities";
     public static final String FIELD_PRIVILEGE_ROLE = "privilegeRole";
     public static final String FIELD_MANAGING_EMPLOYEES = "managingEmployees";
     public static final String FIELD_ACTIVITY_AMOUNT = "activityAmount";


     @Id
     @GeneratedValue
     private Long activityId; //活动ID

     @Length(max = 100)
     private String eventName; //活动名称
    @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd")
     private Date releaseDate; //发布日期
    @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd")
     private Date releaseEndDate; //结束发布日

     @Transient
     private String createdByBy;
    @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd")
     @Transient
     private Date createTime;
     @Length(max = 40)
     private String activeStatus; //活动状态

     @Length(max = 255)
     private String activities; //活动内容

    @Transient
    private String privilege;


     @Length(max = 40)
     private String privilegeRole; //权限角色

     @Length(max = 40)
     private String managingEmployees; //管理员工

     private double activityAmount; //活动金额

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public String getPrivilege() {
        return privilege;
    }

    public void setPrivilege(String privilege) {
        this.privilege = privilege;
    }

    public String getCreatedByBy() {
        return createdByBy;
    }

    public void setCreatedByBy(String createdByBy) {
        this.createdByBy = createdByBy;
    }

    public void setActivityId(Long activityId){
         this.activityId = activityId;
     }

     public Long getActivityId(){
         return activityId;
     }

     public void setEventName(String eventName){
         this.eventName = eventName;
     }

     public String getEventName(){
         return eventName;
     }

     public void setReleaseDate(Date releaseDate){
         this.releaseDate = releaseDate;
     }

     public Date getReleaseDate(){
         return releaseDate;
     }

     public void setReleaseEndDate(Date releaseEndDate){
         this.releaseEndDate = releaseEndDate;
     }

     public Date getReleaseEndDate(){
         return releaseEndDate;
     }

     public void setActiveStatus(String activeStatus){
         this.activeStatus = activeStatus;
     }

     public String getActiveStatus(){
         return activeStatus;
     }

     public void setActivities(String activities){
         this.activities = activities;
     }

     public String getActivities(){
         return activities;
     }

     public void setPrivilegeRole(String privilegeRole){
         this.privilegeRole = privilegeRole;
     }

     public String getPrivilegeRole(){
         return privilegeRole;
     }

     public void setManagingEmployees(String managingEmployees){
         this.managingEmployees = managingEmployees;
     }

     public String getManagingEmployees(){
         return managingEmployees;
     }

    public double getActivityAmount() {
        return activityAmount;
    }

    public void setActivityAmount(double activityAmount) {
        this.activityAmount = activityAmount;
    }
}
