package com.hand.yfsrole.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
@ExtensionAttribute(disable=true)
@Table(name = "yfs_user_role")
public class YUserRole extends BaseDTO {

     public static final String FIELD_SUR_ID = "surId";
     public static final String FIELD_ACTIVITY_ID = "activityId";
     public static final String FIELD_ROLE_ID = "roleId";


     @Id
     @GeneratedValue
     private Long surId;

     private Long activityId; //活动ID

     private Long roleId; //角色ID


     public void setSurId(Long surId){
         this.surId = surId;
     }

     public Long getSurId(){
         return surId;
     }

     public void setActivityId(Long activityId){
         this.activityId = activityId;
     }

     public Long getActivityId(){
         return activityId;
     }

     public void setRoleId(Long roleId){
         this.roleId = roleId;
     }

     public Long getRoleId(){
         return roleId;
     }

     }
